export const sadWords = [
  "sad",
  "unhappy",
  "depressed",
  "miserable",
  "gloomy",
  "despondent",
  "heartbroken",
  "sorrowful",
  "melancholy",
  "downcast",
  "blue",
  "despairing",
  "forlorn",
  "woeful",
  "crestfallen",
  "tearful",
  "disheartened",
  "discouraged",
  "dejected",
  "downhearted",
  "low-spirited",
  "dismal",
  "wretched",
  "mournful",
  "glum",
  "somber",
  "disconsolate",
  "bereft",
  "down",
  "cast down",
  "in the dumps",
  "in despair",
  "down in the mouth",
  "feeling down",
  "feeling blue",
];

export const startEncouragements = [
  "You got this!",
  "Keep going!",
  "Stay strong!",
  "Believe in yourself!",
  "You're doing great!",
  "You're amazing!",
  "Never give up!",
  "Keep pushing forward!",
  "You're capable of amazing things!",
  "You're unstoppable!",
  "Keep the faith!",
  "You're making progress!",
  "You're on the right track!",
  "Stay positive!",
  "You're an inspiration!",
  "Every little step counts!",
  "You're stronger than you know!",
  "You can do anything!",
  "Don't be afraid to shine!",
  "You're destined for greatness!",
];
